# Generated by Django 5.0 on 2023-12-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_created_at_remove_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='delete',
        ),
    ]
